[env:xiao_esp32s3]
platform = espressif32@7.0.1
board = seeed_xiao_esp32s3
board_build.partitions = partitions.csv
framework = arduino
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DFACE_DETECTION_ENABLED=1
lib_deps =
    adafruit/Adafruit BNO055@^1.6.1
    adafruit/Adafruit GPS Library@^1.3.4
    adafruit/Adafruit PWM Servo Driver Library@^3.0.0
    bblanchon/ArduinoJson@^7.2.0
